### ISSUE TITLE
Improve how to handle variants/multiple variant groups

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#10]
I would love if there were a build-in datatype/property editor or another way to handle many variants and different variant groups.

E.g. I once had a company with 27 different shoe sizes (incl. ½ sizes) and it would be difficult to handle variants as tree nodes. Just for 10 products that would be 270 child nodes.

Maybe you could just add or select variants and variant groups on a product and the combinations would be generated? From there you could change price, stock etc. on each variant.

I know you guys could build a custom solution for a specific client that need this and it might be okay with a medium size client with many products, but for a small client it might be harder to convince to client to pay that extra compared with the price of the license.

I think many using Tea Commerce would like to have a built-in support for this and would be willing to pay a small amount to get this developed - I would.

Is this something that could be considered in the future versions of Tea Commerce?

**Comment by TomSteer** [comment]
I agree, this is something that be amazing to have. 

I've been looking at how other eCommerce sites handle variants and variant combinations e.g. size and color and to be honest Merchello does this very well it seems. I know there product data store doesn't use Umbraco nodes but I guess as Bjarne stated you could generate the variant nodes automatically. I also looked at shopify to see how they handled variant combinations and it seems very similar to Merchello.

Thanks
Tom

**Comment by andersburla** [comment]
Tea Commerce 3.1+ has a variant property editor for products
