### ISSUE TITLE
Upgradering from Tea Commerce v2 to v3 - issue with creating giftcard

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#13]
I installed af Tea Commerce 3 in an Umbraco 6.2.4 and Tea Commerce 2.3.2

Now I noticed the property "Lenght" under the tab "Gift cards" for the store was set the null, which means no code was generated and after the first "empty" gift card it returned an exception:

![2014-12-18_22-55-41](https://cloud.githubusercontent.com/assets/2919859/5496975/1fe9c552-870d-11e4-88d1-251f7f49cb24.jpg)

![2014-12-18_22-59-09](https://cloud.githubusercontent.com/assets/2919859/5496979/27841420-870d-11e4-96a6-463a4e401ac5.jpg)

![2014-12-18_23-00-34](https://cloud.githubusercontent.com/assets/2919859/5496981/2d27e3de-870d-11e4-94d9-817306ad6b34.jpg)

I changed the "Lenght" property to 10, but it also changed "Number of days to be valid" to same value.. shouldn't it be possible to set two different values?

![2014-12-18_23-14-43](https://cloud.githubusercontent.com/assets/2919859/5496988/380275ee-870d-11e4-8345-231e275c036b.jpg)

Anyway, after changing this value to 10, I could create a new giftcard:

![2014-12-18_23-13-20](https://cloud.githubusercontent.com/assets/2919859/5497017/7dea7638-870d-11e4-901a-e28ddf20dbea.jpg)

**Comment by bjarnef** [comment]
I think the Length property in Gift cards tab in Store Settings shouldn't allow 0. Maybe it should have a minimum length - at least 1 character otherwise you don't have a gift card code anyway.

**Comment by andersburla** [comment]
Fixed in 3.0.1

**Comment by andersburla** [comment]
This should work in 3.0.0
