### ISSUE TITLE
Missing "totalSavedPrice" and "totalSavedPrice.Formatted"

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#19]
With the marketing module and the API, I can easily get the total discount and total gift card amount. However there doesn't seem to be an easy way to access the total saved price for an order, when you have used both a giftcard and a discount code.

E.g. I have created two giftcards on 50 DKK and 200 DKK .. and a discount code with 10% discount of total price.

I have a property to get total discount and total gift card amount. However if I want the total save price a can add the values, but if I also want the format and currency set i Tea Commerce I have to do some more work. How would you handle this, without hardcode the currency format in the razor or JavaScript code?

Would it make sence to have two properties like "totalSavedPrice" and "totalSavedPrice.Formatted"?

See my case here:
![2014-12-27_15-54-28](https://cloud.githubusercontent.com/assets/2919859/5561592/ff627f64-8de1-11e4-9768-5e9be316e00e.jpg)

In e.g. JavaScript I can add the prices, but I then need a function/helper to get the price **519.5** in the right format.

```
cart.find('#discount').text((parseFloat(order.totalPrice.giftCardsAmount.value) + parseFloat(order.totalPrice.discount.withVat)));
```

**Comment by bjarnef** [comment]
The prices in discounts rules and awards is set to the price excl. or incl. VAT depending on the settings in the store.

Then you can display the total discount (incl. gift cards used):

Razor:
```
@TC.FormatPrice(storeId, (decimal)order.TotalPrice.GiftCardsAmount.Value + (decimal)order.TotalPrice.TotalDiscount.WithVat).Formatted
```

JavaScript:
```
cart.find('#discount').text("- " + TC.formatPrice({ storeId: order.storeId, price: (parseFloat(order.totalPrice.giftCardsAmount.value) + parseFloat(order.totalPrice.totalDiscount.withVat)) }).formatted);
```

**Comment by andersburla** [comment]
Hi Bjarne
Discount and gift card is not the same thing and that is why it is separated. If you like to merge it you can just do that in your special case.

**Comment by bjarnef** [comment]
I know, I just wanted a total sum of the price the customer save, but I manage to do it this way. Maybe something for the documentation?
