### ISSUE TITLE
Property on Discount Code for the price value

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#22]
When you loop through the gift cards it's easy to output the value of the giftcard with the "Amount" property.. however when looping the discount codes there are only they only have "Code" and "IsFulfilled" properties.

If you add multiple discount codes and gift cards, you might want to see how much each represents in the discount. There don't seem to be an easy way to access to value.

I can find the value like this:
```
foreach (var discountCode in discountCodes)
{
    var di = order.TotalPrice.Discounts.ElementAt(0);
    <span class="discountCode">@discountCode.Code @di.WithVatFormatted</span>
}
```

the index "0" should match the loop, so first time 0, then 1, 2.. etc... but you could have three discount codes, where the no. 1 and 3 is on total price og no. 2 on subtotal. Then if I want the discount price for no. 3 it would be order.TotalPrice.Discounts.ElementAt(1); (the second element).. so I can't ensure that the loop match the same same elements in the TotalPrice.Discounts or Subtotal.Discounts arrays.

but I have another code, where the discount is related to Subtotal, so I would have to use order.SubtotalPrice.Discounts ... and the award could have been added to shipment price and payment price aswell.

but I think it only is relevant, when you have a discount code rule for the campaign. Is there another to get the discount price for the matching discount code?

**Comment by andersburla** [comment]
Hi Bjarne

The discount code don't know which awards it will result in and that is why it doesn't have a relation to the discount. Because there can be multiple rules that need to fulfill to give the award. And is it then the discount code or the other rule that gives the discount. And what if a 3 party developer did a new type of award that would give a free product. See the point with how advanced that is? That is the reason its not possible to list the amount for a discount code.

**Comment by bjarnef** [comment]
Hi Anders

Okay, I see that there can be more complex cases, where it could be difficult to tell which rule give the award. I am thinking of a more simple scenario, when a discount code "act" pretty much like a gift card - when I have a fixed amount for a discount code. I have a discount code called NEWYEAR2015 and the award set to 200 DKK of Total Price. So if the discount is added to the order I can see the total discount: 300 and 200 from gift cards and 200 from discount code (I think VAT have been added to the discount too in the case - should the discount fixed prices be set without VAT?
![2015-01-08_13-33-24](https://cloud.githubusercontent.com/assets/2919859/5662555/f696efc0-973a-11e4-9d0b-b70cb4238a3a.jpg)
)

![2015-01-08_12-58-15](https://cloud.githubusercontent.com/assets/2919859/5662240/e2204856-9736-11e4-8b55-2d8734b2fe79.jpg)

Now I have 2 gift cards added and 1 discount code added to the order:

![2015-01-08_13-10-49](https://cloud.githubusercontent.com/assets/2919859/5662326/e7df1654-9737-11e4-92ec-16a53d6972d8.jpg)

If I only had 1 discount and award on total price, I can get it like this below. The problem is I don't know if the award is set on Subtotal or Total price and at which index the element exists:

And the elements in the Discounts property array doesn't have a key like the code - if it had I could get the element with the specific code.
```
foreach (var discountCode in discountCodes)
{
    var di = order.TotalPrice.Discounts.ElementAt(0);
    <span class="discountCode">@discountCode.Code @di.WithVatFormatted</span>
}
```
![2015-01-08_13-17-01](https://cloud.githubusercontent.com/assets/2919859/5662469/a2263ae6-9739-11e4-8fc1-03adcb0b1149.jpg)

If I add multiple discount codes, some with award on Subtotal and some on Total Price and depending on the order the codes is added, I have 1 discount code in Subtotal and 1 discount code in Total price.

![2015-01-08_13-33-24](https://cloud.githubusercontent.com/assets/2919859/5662592/71dc5ad0-973b-11e4-808a-55d12cf5d639.jpg)

Is the a way to archieve this? You know the number of discount codes, but not whether to look in SubtotalPrice or TotalPrice and how many elements in each array.

**Comment by andersburla** [comment]
As talked on email - it wont be possible at the moment to show prices for a discount code as it is decoupled from this information.
