### ISSUE TITLE
Missing Discount Code value in e-mail templates

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#23]
In the e-mail templates, e.g. edit-order.cshtml and email-template-confirmation.cshtml it display the amount of the gift cards used, but it doesn't display any price about the Discount Codes used, e.g. when you use an Discount Code "NEWYEAR2015" with 10% of Subtotal price and if Subtotal is 5.990,00 the Discount for TotalPrice would be 599,00.

Otherwise you might be wondering, where the "missing" subtracted price in the TotalPrice come from.

The part below is already in the template:
```
@if ( Model.TotalPrice.GiftCardsAmount.Value > 0 ) {
          <tr>
            <td colspan="4" align="right">
              @(Model.GiftCards.Count > 1 ? "Gift cards" : "Gift card")
            </td>
            <td style="white-space: nowrap;" align="right">
              @Model.TotalPrice.GiftCardsAmount
            </td>
            <td></td>
          </tr>
}
```

so I have just added this **new** part below the gift card amount:
```
@if ( Model.TotalPrice.Discount.Value > 0M ) {
            <tr>
                <td colspan="4" align="right">
                    @(Model.DiscountCodes.Count > 1 ? "Discount codes" : "Discount code")
                </td>
                <td style="white-space: nowrap;" align="right">
                    @Model.TotalPrice.Discount
                </td>
                <td></td>
            </tr>
}
```

Maybe also add a "-" as text in front to clarify that these prices are subtracted?

**Comment by andersburla** [comment]
The edit-order.cshtml.default and email-template-confirmation.cshtml.default has the new templates for new shops. These contains markup where prices are lined through if there is a discount. So have a look at the new files

**Comment by bjarnef** [comment]
Yes, I did look into these files :) .. edit-order list the giftcard and discount codes used, but before totalprice, both in edit-order and email-template-confirmation it only display gift card amount before the total price.. not the amount of the discount :)

This is from email-template-confirmation.cshtml in the last part

```
@if ( Model.TotalPrice.GiftCardsAmount.Value > 0M ) {
      <tr>
        <td colspan="4" align="right">
          @(Model.GiftCards.Count > 1 ? "Gift cards" : "Gift card")
        </td>
        <td style="white-space: nowrap;" align="right">
          @Model.TotalPrice.GiftCardsAmount
        </td>
      </tr>
    }
    <tr>
      <td colspan="4" align="right">
        <b>Total</b>
      </td>
      <td style="white-space: nowrap;" align="right">
        @if ( Model.TotalPrice.WithPreviousDiscounts.Value != Model.TotalPrice.Value.Value ) {
          <text>(</text><span style="text-decoration: line-through;">@Model.TotalPrice.WithPreviousDiscounts</span><text>)</text>
        }
        <b>
          @Model.TotalPrice
        </b>
      </td>
    </tr>
  </table>
```

it is missing this part before total price:

```
@if (Model.TotalPrice.Discount.Value > 0M) {
        <tr>
            <td colspan="4" align="right">
                @(Model.DiscountCodes.Count > 1 ? "Rabatkoder" : "Rabatkode")
            </td>
            <td style="white-space: nowrap;" align="right">
                - @Model.TotalPrice.Discount
            </td>
        </tr>
    }
```

**Comment by andersburla** [comment]
Its not missing these as the discounts are displayed multiple places in the order view. It has a before and after discount price with a line through the before price. So that is why the total discount isn't listed.

**Comment by bjarnef** [comment]
Well, yes you can see the total price before and after discount (incl. gift cards). Saved price from gift cards is listed, but I don't think it is clear where the "missing" price you save is from. You can see you have got some discount, but the listed prices together are not equal to the total price, when you e.g. have used a discount code. I think there is missing a part (the discount) to make it clear that the "missing" price is a discount you got. I only display this, if any discount has been added to the order like the case is with gift cards.
The discount code should have been 250DKK, just an previously discount code, where the discount code value was 250 and become 312,50 incl. VAT.

The yellow part here is my addition:
![2015-02-01_14-58-46](https://cloud.githubusercontent.com/assets/2919859/5992329/39721ebc-aa25-11e4-9618-f4aa0d5dedf8.jpg)

and in the confirmation e-mail compared to the default confirmation e-mail in Tea Commerce:
![2015-02-01_14-59-32](https://cloud.githubusercontent.com/assets/2919859/5992333/6605c6e0-aa25-11e4-8196-25c5267b2688.jpg)

![2015-02-01_15-07-41](https://cloud.githubusercontent.com/assets/2919859/5992334/6a90cce6-aa25-11e4-98b3-c9f295c8faa7.jpg)
