### ISSUE TITLE
Quantity on edit order view in Umbraco doesn't appear to work

### ISSUE THREAD

**Issue by TomSteer** [TeaCommerce/Tea-Commerce-for-Umbraco#29]
When you change the quantity of an orderline in the edit-order screen inside umbraco and hit save the quantity has been incremented but the prices don't seem to change and also it doesn't seem to take into consideration the stock as the stock for this product 1 yet I could increase it to 2. Or maybe it does take it into consideration and that is why the prices don't change but if that is the case then it shouldn't stay incremented after you save the order.

Thanks,

Tom

**Comment by andersburla** [comment]
There should be an option for an order status to recalculate a finalized order, but the UI for configuring that is not implemented - which is a bug :)
