### ISSUE TITLE
Security section - allow user to access Marketing without accessing Settings

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#3]
Under the Security node if I just check the "Marketing" checkbox it doesn't check the store checkbox, but if I reload the view it's checked.. but I can't just checked only the store + marketing ... I also have to check the Settings checkbox.. so for my editor user it either doesn't have access to marketing or it has access to marketing, but also to settings.

**Comment by andersburla** [comment]
Fixed in 3.0.1
