### ISSUE TITLE
Umbraco 7.2 bug with order search page

### ISSUE THREAD

**Issue by TomSteer** [TeaCommerce/Tea-Commerce-for-Umbraco#31]
I've just tried upgrading a site to 7.2.1 and when I navigate to the Tea Commerce order search page in Umbraco I get the following error:

An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS0104: 'Constants' is an ambiguous reference between 'ClientDependency.Core.Constants' and 'TeaCommerce.Umbraco.Application.Constants'

Thanks,

Tom

**Comment by andersburla** [comment]
What version of Tea Commerce do you use?

**Comment by tommyflint** [comment]
I was using v3

**Comment by andersburla** [comment]
Just installed 3.0 on 7.2.1 and it worked out of the box. Was your an update or?

**Comment by tommyflint** [comment]
That's odd... It was an upgrade from 7.1.8 (I think) I'm assuming your test was before Richard's commit ;)

**Comment by andersburla** [comment]
Yes - I can't reproduce it. So we will close it and hope Richards commit will fix the rare cases :)
