### ISSUE TITLE
Node names in tree sometimes don't match User language

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#37]
Sometimes I have seen that the node names in the tree don't always match the User language.

E.g. here I am logged in as admin user which is set to English (UK), but the node names are in Danish. But there is another user created which use Danish.

Using Umbraco 6.2.4 and Tea Commerce 3.0.0

![2015-03-01_13-47-27](https://cloud.githubusercontent.com/assets/2919859/6430794/e3b8fc42-c019-11e4-9f7a-609d84fa11a6.jpg)

However when I browsed to another section and came back it was updated.

![2015-03-01_13-51-38](https://cloud.githubusercontent.com/assets/2919859/6430799/3ee4d3ac-c01a-11e4-858c-dc54fd2854b6.jpg)

Have you guys seen that before?

**Comment by andersburla** [comment]
Not experienced this before. Maybe upgrade to Umbraco 7 and see if its fixed.

**Comment by bjarnef** [comment]
It also happpens in a clean Umbraco 7.3.1 with Tea Commerce 3.0.7 .. when you switch user language it doesn't seems to switch the language correct ..

![image](https://cloud.githubusercontent.com/assets/2919859/11430761/c1e7a126-948b-11e5-8466-caf666d9959c.png)
