### ISSUE TITLE
Error when deleting shipping/payment image

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#4]
In Umbraco 7 you get an error after you pick an image for a Shipping Method and the click delete to remove the image. Might also be an issue for Payment methods.

**Comment by andersburla** [comment]
I see that, but I think its a bug with Umbraco as we use the ContentPicker of Umbraco. The href is ../shared/# and so is the "choose" link. But the choose link works

**Comment by mattbrailsford** [comment]
Fixed in 2e2b70a. Technically this is a core issue, but I've added some code to intercept the buttons on the content picker and have them preventDefault on the event.
