### ISSUE TITLE
Update edit-order.cshtml with discount codes in total column

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#40]
In edit-order.cshtml in total column in list the gift cards used, but not discount codes used..

It does list discounts codes below "Order lines", however if discount codes are used, it might not be clear exactly how the final total price is calculated because you are not seing the subtracted price for discount codes.

I have modified the template with an addtional row for subtracted discount codes, but I think it should be default and I have added a minus in front to make it clear that it is a price that is subtracted:

```
@if ( Model.TotalPrice.GiftCardsAmount.Value > 0 ) {
          <tr>
            <td colspan="4" align="right">
              @(Model.GiftCards.Count > 1 ? "Gift cards" : "Gift card")
            </td>
            <td style="white-space: nowrap;" align="right">
              - @Model.TotalPrice.GiftCardsAmount
            </td>
            <td></td>
          </tr>
        }
        @if ( Model.TotalPrice.Discount.Value > 0 ) {
            <tr>
                <td colspan="4" align="right">
                    @(Model.DiscountCodes.Count > 1 ? "Discount codes" : "Discount code")
                </td>
                <td style="white-space: nowrap;" align="right">
                    - @Model.TotalPrice.Discount
                </td>
                <td></td>
            </tr>
        }
```

Futhermore I have also added it to email-template-confirmation.cshtml

**Comment by andersburla** [comment]
The system don't know which discount codes gives which discounts. So that is why you can't add it like that. The discounts can be for 1000 different things - not only discount codes.

**Comment by bjarnef** [comment]
Hi Anders..

Yes, but you can add to discount to the summary then. Right now it only list the GiftCardsAmount .. and when you summarize that order lines it doesn't match the total price, because the discount is "missing".

At least this will show the discount price, if any discount is added to the order (no matter it is a discount code or another award given).
```
@if ( Model.TotalPrice.GiftCardsAmount.Value > 0 ) {
          <tr>
            <td colspan="4" align="right">
              @(Model.GiftCards.Count > 1 ? "Gift cards" : "Gift card")
            </td>
            <td style="white-space: nowrap;" align="right">
              - @Model.TotalPrice.GiftCardsAmount
            </td>
            <td></td>
          </tr>
        }
        @if ( Model.TotalPrice.Discount.Value > 0 ) {
            <tr>
                <td colspan="4" align="right">
                    Discount
                </td>
                <td style="white-space: nowrap;" align="right">
                    - @Model.TotalPrice.Discount
                </td>
                <td></td>
            </tr>
        }
```

**Comment by bjarnef** [comment]
@andersburla please consider these two examples:

![image](https://cloud.githubusercontent.com/assets/2919859/11454871/e9f7dd74-963f-11e5-9b54-1727ed20b15a.png)

here the discount been given on unit price, but sometimes on subtotal or total price and it might not be clear how much have been given in discount or from gift cards.

Modified:

```
@if ( Model.TotalPrice.GiftCardsAmount.Value > 0 ) {
          <tr>
            <td colspan="4" align="right">
              @(Model.GiftCards.Count > 1 ? "Gift cards" : "Gift card")
            </td>
            <td style="white-space: nowrap;" align="right">
              - @Model.TotalPrice.GiftCardsAmount
            </td>
            <td></td>
          </tr>
        }
        @if ( Model.TotalPrice.TotalDiscount.Value > 0 ) {
            <tr>
                <td colspan="4" align="right">
                    Discount
                </td>
                <td style="white-space: nowrap;" align="right">
                    - @Model.TotalPrice.TotalDiscount
                </td>
                <td></td>
            </tr>
        }
```
![image](https://cloud.githubusercontent.com/assets/2919859/11454882/aa2e9178-9640-11e5-8e0e-cb6550354235.png)

if not listing it in the summary, I think it should list the discount codes (or just discounts) and how much have been subtracted.. and the gift cards and how much have been subtracted. But only if any have been used.
