### ISSUE TITLE
Use different tree icons for active/deactive discount codes

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#5]
For discount codes maybe change the tree node icon to a red tag icon, when it is not active or valid anymore? and maybe the marketing root node could be used to list the created discount codes?

**Comment by bjarnef** [comment]
@andersburla 

I have installed Tea Commerce v. 3.0.7 on Umbraco 6.2.4, but I don't see #33 having any effect?

**Comment by andersburla** [comment]
Matt did some changes to the tree dimming campaigns that are not active
