### ISSUE TITLE
GetAllFinalizedOrdersAsXml has been removed

### ISSUE THREAD

**Issue by timgaunt** [TeaCommerce/Tea-Commerce-for-Umbraco#52]
We used GetAllFinalizedOrdersAsXml to search for orders by email address but it's been removed in one of the recent builds. How can we search for orders by email address?

**Comment by TomSteer** [comment]
Hey Tim... You have to query the database manually now as far as I am aware. I've just used petapoco in the past to query for the order ids I want and then used the method GetOrders on the TeaCommerceHelper, passing in the ids. Cheers Tom

**Comment by timgaunt** [comment]
Cheers @TomSteer, I had a feeling that may be the case, shame they didn't document that it was removed.

**Comment by runegronkjaer** [comment]
The breaking change have now been added to the revision history. Sorry for the inconvenience.
