### ISSUE TITLE
jQuery errors in Tea Commerce section

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#53]
Based on the demo on demo.teacommerce.net then console shows errors for Tea Commerce section, e.g. in  SearchOrders.aspx

It seems it rely on the old .live() function - it should be replaced by the .on() function http://api.jquery.com/on/ 

I am not sure if any Umbraco v6 version use a version of jQuery before v.1.7?

![image](https://cloud.githubusercontent.com/assets/2919859/20899707/d46edc7a-bb2b-11e6-96e6-ab2a19797b51.png)

**Comment by andersburla** [comment]
Hi Bjarne. You can just correct it and make a PR in the dev branch :)
We support only Umbraco 7.1+ now so you can use what jQuery version that Umbraco 7.1+ uses.

**Comment by mattbrailsford** [comment]
@bjarnef I can't seem to replicate this. I know it was a while ago, but do you recall the steps to replicate?

**Comment by bjarnef** [comment]
@mattbrailsford as I remember og was either when accessing the orders overview and when making a search for orders.

**Comment by mattbrailsford** [comment]
@bjarnef hmm, it looks to work ok on the demo site. I've search the codebase and I can find .live jquery events, but not sure whether to change them for backwards compat. I'm guesing they still work without error because the back office includes a JQMIGRATE script, which I'm wondering whether it didn't before hence the errors?

**Comment by mattbrailsford** [comment]
If you have no objects, I may just close this issue down and assume this got resolved with an Umbraco update?

**Comment by bjarnef** [comment]
@mattbrailsford yeah, not sure how I got this error. Maybe it was on a specific previous v7 version.

**Comment by mattbrailsford** [comment]
I think it might have been. Will close this issue off for now then. Thank you for reporting it never the less. 👍
