### ISSUE TITLE
SQL Exception on updating orderlines very fast

### ISSUE THREAD

**Issue by HerrNiklasRaab** [TeaCommerce/Tea-Commerce-for-Umbraco#58]
Hello,

if i am updating the same orderline 2 times in 10 - 100ms then following error occoured. With Umbraco 7.5 it worked, but with 7.6 it is not possible.
![fast](https://cloud.githubusercontent.com/assets/28401593/25902881/1c63d578-359b-11e7-9ab2-b5b709bd8cfb.PNG)

Does anyone know why?

Niklas

**Comment by suedeapple** [comment]
There are some breaking changes in v7.6, which related to Database Connections.  I think TC,  has hit one of these...

https://our.umbraco.org/documentation/Getting-Started/Setup/Upgrading/760-breaking-changes

Database (U4-9201)

Might need Anders to properly take a look

**Comment by andersburla** [comment]
Hmm we use our own instance of PetaPoco in the Tea Commerce Core. So how should Umbraco be able to play with that? :)
Can one of you send me a specific web solution that I can run in Visual Studio where it fails 100% of the times - then I can try and debug what is happening.

**Comment by HerrNiklasRaab** [comment]
Now its working, properbly because auf the Umbraco Update 7.6.1

**Comment by andersburla** [comment]
I'll close the issue. Let me know if it starts again
