### ISSUE TITLE
Regex issue sending Emails

### ISSUE THREAD

**Issue by MichelCollard** [TeaCommerce/Tea-Commerce-for-Umbraco#62]
Hi,

We are unable to send emails with an email address that looks like : mail-@domain.com.
The following error will appear:

> ERROR TeaCommerce.Api.Models.EmailTemplate - Error sending Confirmation email template. Order id: [GUID]. Cart number: CART-123456
> System.InvalidOperationException: A recipient must be specified.
>    at System.Net.Mail.SmtpClient.Send(MailMessage message)
>    at TeaCommerce.Api.Models.EmailTemplate.Send[T](T model, String customerEmail, Nullable`1 languageId)

I think the regex is located here TeaCommerce.Api.Common.ValidationExtensions.cs.

p.s.
We are using TeaCommerce version 3.2.2

**Comment by andersburla** [comment]
You are right. That is because of that regex. Thanks for reporting. Maybe you can just make the email: mail-1@domain.com. That would work for a workaround. Could just be an alias for the mailbox

**Comment by mattbrailsford** [comment]
Next release will have it relaxed to a more forgiving `^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,9}$`
