### ISSUE TITLE
Add rule in Marketing return errors

### ISSUE THREAD

**Issue by bjarnef** [TeaCommerce/Tea-Commerce-for-Umbraco#65]
I noticed in the demo store https://demo.teacommerce.net that "Add rule" returns errors.

If no rule has been selected ("Choose a rule" option), it return the following console error.

![image](https://user-images.githubusercontent.com/2919859/37138896-2a05a93c-22ac-11e8-8c95-b8c4c6bfd3aa.png)

**Comment by mattbrailsford** [comment]
Fixed in commit bea07b7
