### ISSUE TITLE
TeaCommerce should support rendering partial views and not just macroscripts

### ISSUE THREAD

**Issue by arknu** [TeaCommerce/Tea-Commerce-for-Umbraco#79]
TeaCommerce currently has a few places where it will dynamically render using a macroscript file. As these files are deprecated, I'd like to use partial views instead. However, TeaCommerce is currently limited to only macroscripts.

This can be remedied by updating the TemplateFileLocator and TemplateRenderer to support files in ~/Views/Partials as well.

I have a PR mostly ready to go, should be ready either today or tomorrow. This will support Partial Views in addition to macroScripts, so it is still backwards compatible.

Of course, for Umbraco 8 macroScripts have been removed entirely, but I still think this is worth doing for v7.

**Comment by mattbrailsford** [comment]
Hey @arknu. Yea, there is a lot that would be nice to update but my current mindset is that if it's not broken in v7, to leave as is. But of course, if it's something you'd like to tackle and submit a PR for I would be more than happy to review it / merge it in.

**Comment by arknu** [comment]
@mattbrailsford I have it working in a site now, so I just need to refactor the code a bit and make it a PR.

**Comment by arknu** [comment]
As promised, a PR to add support for rendering MVC partial views: #80

**Comment by mattbrailsford** [comment]
Fixed in merged PR #80

Thanks @arknu 👍
