### ISSUE TITLE
Broken help links

### ISSUE THREAD

**Issue by PeteDuncanson** [TeaCommerce/Tea-Commerce-for-Umbraco#94]
![image](https://user-images.githubusercontent.com/1674590/65605100-70b23780-dfa0-11e9-818f-26edea945471.png)

Not essential this one but nice for continuity of business I guess. On my help screen there are some links which are broken:

- https://documentation.teacommerce.net/ doesn't exist
- https://teacommerce.net/en/documentation/revision-history/ throws an error

Easy to fix with some redirects I guess.

**Comment by mattbrailsford** [comment]
@PeteDuncanson ahhh, good call. I think we updated these in newer releases, but of course, people on older versions will be wrong. Will implement some redirects accordingly 👍

**Comment by mattbrailsford** [comment]
Rewrites have been setup. Thanks for the heads up 👍
