### ISSUE TITLE
Trouble navigating back to a list of orders after editing an order

### ISSUE THREAD

**Issue by PeteDuncanson** [TeaCommerce/Tea-Commerce-for-Umbraco#95]
Happening in v3.2.5 on Umbraco V7.12.2

![image](https://user-images.githubusercontent.com/1674590/65605427-fcc45f00-dfa0-11e9-9dfa-d446e54da4f0.png)

Drilling down to an "Completed" order via the "Completed" order tree item/view, if I click into any order and then click back on the "Completed" tree icon it doesn't take me back to the listing of orders. Infact it does nothing. Its like that link is just dead.

I can click any of hte other status views ("New", "On Hold", etc.) and it will list those real fast and then I can click on the "Completed" view again. I could also just press the back button but thats not always an option after a Save it seems. 

Slowed me up no end today until I worked out nothing was happening!

**Comment by mattbrailsford** [comment]
@PeteDuncanson good point. 

This occurs because the edit list + edit screen both use the same iframe and don't change the angular route, so they just change the URL of Iframe. Will see if there is a way to separate them so they have their own routes 👍

**Comment by mattbrailsford** [comment]
Fixed in 3.4.0
